// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IIcRoundMinus: typeof import('~icons/ic/round-minus')['default']
    IIcRoundPlus: typeof import('~icons/ic/round-plus')['default']
    IMdiAlertCircleOutline: typeof import('~icons/mdi/alert-circle-outline')['default']
    IMdiCalendar: typeof import('~icons/mdi/calendar')['default']
    IMdiCart: typeof import('~icons/mdi/cart')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiCheckAll: typeof import('~icons/mdi/check-all')['default']
    IMdiCheckBold: typeof import('~icons/mdi/check-bold')['default']
    IMdiCheckboxBlankCircle: typeof import('~icons/mdi/checkbox-blank-circle')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiCloseBold: typeof import('~icons/mdi/close-bold')['default']
    IMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal')['default']
    IMdiMapMarker: typeof import('~icons/mdi/map-marker')['default']
    IMdiSearch: typeof import('~icons/mdi/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
