// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    ICarbonSearch: typeof import('~icons/carbon/search')['default']
    IIcCalendar: typeof import('~icons/ic/calendar')['default']
    IIcClose: typeof import('~icons/ic/close')['default']
    IIcCloseBold: typeof import('~icons/ic/close-bold')['default']
    IIcRoundMinu: typeof import('~icons/ic/round-minu')['default']
    IIcRoundMinus: typeof import('~icons/ic/round-minus')['default']
    IIcRoundPlus: typeof import('~icons/ic/round-plus')['default']
    IIcRoundPulus: typeof import('~icons/ic/round-pulus')['default']
    IMdiAlertCircleOutline: typeof import('~icons/mdi/alert-circle-outline')['default']
    IMdiAlertOutline: typeof import('~icons/mdi/alert-outline')['default']
    IMdiCalendar: typeof import('~icons/mdi/calendar')['default']
    IMdiCalendarBlank: typeof import('~icons/mdi/calendar-blank')['default']
    IMdiCart: typeof import('~icons/mdi/cart')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiCheckBold: typeof import('~icons/mdi/check-bold')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiCloseBold: typeof import('~icons/mdi/close-bold')['default']
    IMdiCloseThick: typeof import('~icons/mdi/close-thick')['default']
    IMdiError: typeof import('~icons/mdi/error')['default']
    IMdiMapCalendar: typeof import('~icons/mdi/map-calendar')['default']
    IMdiMapMarker: typeof import('~icons/mdi/map-marker')['default']
    IMdiMinu: typeof import('~icons/mdi/minu')['default']
    IMdiMinus: typeof import('~icons/mdi/minus')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiSearch: typeof import('~icons/mdi/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
